# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 958699eb2fd2ee1e030e9943fd18aaf9859b19e544430001d21bfef143dd795256874db04565f19f0e1aade0a0ccdd3032b333ca8b7d988b65da10e1e7d17a23

test:
  secret_key_base: e235efb2750d01cb5c8a91c85136913fb85bce23e3d5cf73d8b077d87f869f4ce66e3173dad3457388568ed21749da0a3e988960b79c9e94d54dbcf763254bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
